[loggers]
keys=root

[handlers]
keys=console,file

[formatters]
keys=precise

[logger_root]
level=WARNING
handlers=console,file

[handler_console]
class=StreamHandler
level=NOTSET
formatter=precise
args=(sys.stderr,)

[handler_file]
class=handlers.RotatingFileHandler
level=NOTSET
formatter=precise
args=("logs/visionair.log", "a", 10485760, 5)

[formatter_precise]
format=%(asctime)s [%(relativeCreated)9d] - %(name)-7.7s %(levelname)-7s : %(message)s